// examples/vue-test/src/App.vue
<script setup lang="ts">
import { ref } from 'vue'

const count = ref(0)
const increment = () => count.value++
</script>

<template>
  <div class="vue-container">
    <h1>Vue 3 Support Verified!</h1>
    <button @click="increment">Count is: {{ count }}</button>
  </div>
</template>

<style scoped>
.vue-container {
  font-family: sans-serif;
  text-align: center;
  padding: 2rem;
}
button {
  padding: 10px 20px;
  font-size: 1.2rem;
  cursor: pointer;
}
</style>

// src/builder/ui/App.svelte
<script lang="ts">
  let count = 0;
  const increment = () => count += 1;
</script>

<main>
  <h1>NextGen Builder</h1>
  <div class="card">
    <button on:click={increment}>
      count is {count}
    </button>
    <p>
      Edit <code>src/builder/ui/App.svelte</code> and save to test HMR
    </p>
  </div>
</main>

<style>
  main {
    font-family: 'Inter', sans-serif;
    text-align: center;
    padding: 2rem;
  }
  h1 {
    color: #646cff;
  }
  .card {
    padding: 2em;
  }
</style>
