// examples/svelte5-test/src/App.svelte
<script>
    let count = $state(0);
</script>

<main>
    <h1>🔥 Urja Build Tool - Svelte 5 Test</h1>
    <p>Framework: <strong>Svelte 5.x (Runes)</strong></p>
    <p>Status: ✅ Fine-grained Reactivity ($state) Verified</p>

    <button onclick={() => count++}>
        Rune-based Count: {count}
    </button>
</main>

<style>
    main {
        padding: 2rem;
        font-family: "Outfit", sans-serif;
        text-align: center;
    }
    h1 {
        color: #ff3e00;
    }
    button {
        font-size: 1.2rem;
        padding: 1rem 2rem;
        border-radius: 50px;
        background: linear-gradient(135deg, #ff3e00 0%, #ff8e53 100%);
        color: white;
        border: none;
        cursor: pointer;
        box-shadow: 0 10px 20px rgba(255, 62, 0, 0.3);
        transition: transform 0.2s;
    }
    button:active {
        transform: scale(0.95);
    }
</style>

// examples/vue-test/src/App.vue
<script setup lang="ts">
import { ref } from 'vue'

const count = ref(0)
const increment = () => count.value++
</script>

<template>
  <div class="vue-container">
    <h1 style="color: #42b883">🖖 Urja Build Tool - Vue 3 Test</h1>
    <p>Framework: <strong>Vue 3.x (SFC + Script Setup)</strong></p>
    <p>Status: ✅ Verified Compatible</p>
    <button @click="increment">Interactive Count: {{ count }}</button>
  </div>
</template>

<style scoped>
.vue-container {
  font-family: sans-serif;
  text-align: center;
  padding: 2rem;
}
button {
  padding: 10px 20px;
  font-size: 1.2rem;
  cursor: pointer;
}
</style>
